Feature eapp 19 404 error page
KoushikMallik-developer/ecom-app-v3 pull request #7
Opened 2023-12-30 08:48 UTC by animeshrick

### 404 error page

> [JIRA Ticket:[ ECOMAPP - 1234 ](https://schoolbook.atlassian.net/browse/ECOMAPP-1234)](https://shoppixa.atlassian.net/browse/EAPP-19)

**What was the problem:**
404 Error Page -- Page not found with any anonymous URL

**How was this solved:**
Adding custom 404 page design

**Features:**
- Try it locally http://localhost:4000/puchi
- Showing an UI

**Services to be impacted:**
NONE

- `ecom-app`

**Example Code or Screenshot:**
![404-page](https://github.com/KoushikMallik-developer/ecom-app-v3/assets/43946793/7ebbcb6a-1d1a-43e4-8c5f-623f4e57fa86)

**_For the PR Creator_**

- [ ] Filled out entirely of PR Template.
- [ ] Changes meet acceptance criteria defined in ticket.
- [ ] Unit Tests Passed. :tada:
- [ ] Tested on DEV Env.
- [ ] Tested on QA Env.

2023-12-30 10:37 UTC, KoushikMallik-developer requested changes

2023-12-30 10:37 UTC, KoushikMallik-developer commented on src/components/home_page/categories.tsx
> +      const listGroupStyle : CSS.Properties = {
Please keep all the codes in the particular way, CSS should be in a .css file and this style should be imported here.

2023-12-30 10:37 UTC, KoushikMallik-developer commented on src/index.css
> +/* ::-webkit-scrollbar {
Please remove any unwanted or commented code.

2023-12-30 10:37 UTC, KoushikMallik-developer commented on src/types/user_types/user.ts
> +type User = {
Please add `delivery_address` field also.

2023-12-30 10:37 UTC, KoushikMallik-developer commented on src/components/404_error/page_not_found.tsx
> +const NotFoundPage = () => {
please follow the naming convention. You can make it `Error404Page`.

2023-12-30 10:37 UTC, KoushikMallik-developer commented on src/components/404_error/404.png
Please move this file to the particular assets folder.

2023-12-31 09:37 UTC, animeshrick commented on src/types/user_types/user.ts
> +type User = {
There is no use of User Type so be as it is

2023-12-31 09:49 UTC, KoushikMallik-developer commented on src/types/user_types/user.ts
> +type User = {
if there is no use of user type in this page then remove it from the PR.

2024-01-03 16:21 UTC, merged